#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/managersys?characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: zaichiyikoua1
    # 连接池配置
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数